### PR TITLE
Curl SSL

### PR DESCRIPTION
**Pull request by xnukes**
You can now disable curl ssl.

### CODE REVIEW

**Comment by uestla** [comment]
Hi @xnukes and thanks for your contribution :-)

Since this is the second issue about certificates, I'm thinking maybe we should make this more general.

Right now the library is tightly bound with cURL extension, but the request could be done in many different ways (using streams or simple yet ugly `file_get_contents()` function).

So from the above I think it would be cool to have some `IRequester` interface and basic implementations like `CurlRequester` etc.

You could then write your own requester where certificates verification would be disabled.

**Comment by xnukes** [comment]
okey, this is great idea :)

I go to write the interface IRequester and two class implement this requester (curl, simple).¨

When I finish, I will send a pull request.

**Comment by uestla** [comment]
I'm actually preparing more robust interfaces so that `Validator` won't be directly dependent on `Nette\Http\Request` so maybe you can wait a bit with that PR ;-)

**Comment by uestla** [comment]
@xnukes I just added the requester layer.

You should be able to set any cURL option now, please see

https://github.com/uestla/ReCaptchaControl#curlrequester

Could you please test it?

Thanks!

**Comment by uestla** [comment]
ping @xnukes

**Comment by xnukes** [comment]
hi, sorry , i have too projects and no more time for this. I'll try to see it for a week.

**Comment by uestla** [comment]
Any update, @xnukes ?

I'm thinking about releasing new major version.

**Comment by xnukes** [comment]
Hi, please wait today. I have now opened IDE and go to coding. :)

**Comment by xnukes** [comment]
Hi, now is ok. You have refactoring code to excelent 👍 I have added only how to disabled curl ssl in Readme

**Comment by uestla** [comment]
Thanks for testing.

To be honest, I see correct SSL settings on dev's machine as more important than disabling their verification. Hence I don't think it should be explicitely shown in README.

But anyway, thank you for your time, I'm gonna release new version soon :-)

**Pull request closed without merging**
