### PR TITLE
Return type hint (nette 3.0 compatibility)

### PR DESCRIPTION
**Pull request by peldax**
Also incremented minimal php version (to ensure return type hints are supported).

### CODE REVIEW

**Comment by uestla** [comment]
Thank you, @peldax ! I'll merge this into new 8.x branch.

Could you please upgrade whole code-base so all methods have PHP7 typehints (not just one) and also add `declare(strict_types = 1);`?

Also please squash it into single commit (something like `upgraded for Nette 3.0 & PHP7.1+`).

**Comment by peldax** [comment]
This is just a quick hotfix I created during codebase upgrade. I will add more strictness afterwards - after checking that everything is working correctly.

**Comment by uestla** [comment]
I see and understand that, but it would be much nicer to have the library updated all at once, not just a single method.

**Comment by peldax** [comment]
@uestla I added declare strict and typehints to all possible files/methods.

There is one BC break - `IRequester::post()` returns `?string` instead of `string|false`.

**Comment by peldax** [comment]
Please make the merge using --squash option, I made some changes using web interface and completely missed your comment (noticed just now, while re-reading).

**Comment by uestla** [comment]
@peldax I've merged it and made some extra updates (strict types in tests as well, etc.).

Could you please test dev-master and check that it's working for you?

**Comment by uestla** [comment]
ping @peldax

**Comment by peldax** [comment]
Hi, sorry for long response, yes, I can confirm the recaptcha is  working for me, validation passes without problems.

**Comment by uestla** [comment]
@peldax Thank you.

Released as [8.0.0](https://github.com/uestla/ReCaptchaControl/releases/tag/8.0.0) :)

**Pull request closed without merging**
